# Generated by Django 5.2.17 on 2026-09-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='الاسم')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الميلاد')),
                ('is_deceased', models.BooleanField(default=False, verbose_name='متوفى')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الوفاة')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف')),
                ('house_location', models.URLField(blank=True, default='', max_length=500, verbose_name='موقع المنزل')),
                ('education', models.CharField(blank=True, default='', max_length=255, verbose_name='التعليم')),
                ('occupation', models.CharField(blank=True, default='', max_length=255, verbose_name='المهنة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tree.person', verbose_name='الأب')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_by_mother', to='tree.person', verbose_name='الأم')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'أشخاص',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='الحقل')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='القيمة الجديدة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='tree.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'سجل تعديل',
                'verbose_name_plural': 'سجلات التعديل',
                'ordering': ['-created_at'],
            },
        ),
    ]
